In [24]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.23.1-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 1.5 MB/s eta 0:00:00a 0:00:010m
Collecting scikit-learn>=1.0.2
  Downloading scikit_learn-1.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 2.6 MB/s eta 0:00:0000:0100:01
Collecting scipy>=1.2.1
  Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 MB 5.1 MB/s eta 0:00:0000:0100:01
Collecting joblib>=0.13.2
  Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 KB 3.9 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.16.2 in /usr/lib/python3/dist-packages (from mlxtend) (1.21.5)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.5.3)
Collecting matplotlib>=3.0.0
  Downloading matplotlib-3.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 5.5 MB/s eta 0:00:0000:0100:01
Collecting fonttools>=4.22.0
  Downloading fonttools-4.53.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 5.0 MB/s eta 0:00:0000:0100:01
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 5.3 MB/s eta 0:00:00a 0:00:01
Collecting contourpy>=1.0.1
  Downloading contourpy-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (305 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 305.2/305.2 KB 3.4 MB/s eta 0:00:00a 0:00:01
Collecting numpy>=1.16.2
  Downloading numpy-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 5.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (23.0)
Requirement already satisfied: pillow>=8 in /usr/lib/python3/dist-packages (from matplotlib>=3.0.0->mlxtend) (9.0.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=0.24.2->mlxtend) (2022.1)
Collecting threadpoolctl>=3.1.0
  Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Installing collected packages: threadpoolctl, numpy, kiwisolver, joblib, fonttools, cycler, scipy, contourpy, scikit-learn, matplotlib, mlxtend
Successfully installed contourpy-1.2.1 cycler-0.12.1 fonttools-4.53.1 joblib-1.4.2 kiwisolver-1.4.5 matplotlib-3.9.2 mlxtend-0.23.1 numpy-2.1.0 scikit-learn-1.5.1 scipy-1.14.1 threadpoolctl-3.5.0

In [77]:
import os
os.chdir(os.path.expanduser("/home/creal/Desktop/REPOS/data_analytics/development"))

In [78]:
import pandas as pd
df=pd.read_parquet('parquet/eventos_transformados.parquet.gzip')  
df

,timestamp,visitorid,event,itemid,transactionid,fechahora,nombre,apellido,nacimiento,genero,...,ciudad,correo,telefono,categoria_id,nombre_producto,marca_id,volumen,precio,marca,categoria
0,1433221078505,158090,addtocart,10572,NaN,2015-06-02 04:57:58.505,Craig,Sullivan,2/4/61,Male,...,Alto do Estanqueiro,csullivan2d@wsj.com,351-(640)148-2850,1.0,Buchanan's Red Seal,1.0,750,126.75,Diageo Americas,SCOTCH WHISKIES
1,1433222147345,1076270,view,262799,NaN,2015-06-02 05:15:47.345,Roger,Franklin,5/10/76,Male,...,Kungsbacka,rfranklin1m@webeden.co.uk,46-(531)558-4009,1.0,Johnnie Walker Gold Label Reserve,1.0,750,67.49,Diageo Americas,SCOTCH WHISKIES
2,1433224644638,361387,view,43485,NaN,2015-06-02 05:57:24.638,Stephen,Duncan,12/16/48,Male,...,Tongjing,sduncan3j@free.fr,86-(321)524-9060,4.0,Tanqueray Rangpur Gin,1.0,750,19.13,Diageo Americas,IMPORTED DRY GINS
3,1433221740333,712443,view,346655,NaN,2015-06-02 05:09:00.333,Nevile,Mourant,10/28/98,Male,...,Pretoria,nmourantoj@cnn.com,631-907-1374,11.0,Malt Scotch Sampler,1.0,603,52.50,Diageo Americas,SINGLE MALT SCOTCH
4,1433221941632,599528,addtocart,356475,NaN,2015-06-02 05:12:21.632,Samuel,Ward,4/6/89,Male,...,Wangjing,sward0@tamu.edu,86-(786)608-5061,9.0,Crown Royal Honey,1.0,750,22.49,Diageo Americas,CANADIAN WHISKIES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160467,1438398995087,1278874,view,36972,NaN,2015-08-01 03:16:35.087,Gunner,Lagneaux,5/31/87,Male,...,Kopayhorod,glagneauxig@macromedia.com,273-813-3094,42.0,Sobieski Espresso,69.0,750,5.33,"Imperial Brands, Inc.",IMPORTED VODKA - MISC
160468,1438399205822,118200,view,174923,NaN,2015-08-01 03:20:05.822,Allix,Scholling,7/6/89,Female,...,ÊtÝnovice,aschollingjr@prnewswire.com,649-690-1072,45.0,Familia Camarena Silver,18.0,750,15.00,E AND J GALLO WINERY,TEQUILA
160469,1438402186555,175890,view,396732,NaN,2015-08-01 04:09:46.555,Darb,Ferrarello,6/4/96,Male,...,Lyon,dferrarelloly@va.gov,956-201-3106,17.0,Seagram's Pineapple Twisted Mini,7.0,500,4.95,Pernod Ricard USA/Austin Nichols,AMERICAN DRY GINS
160470,1438400558113,118200,view,174923,NaN,2015-08-01 03:42:38.113,Allix,Scholling,7/6/89,Female,...,ÊtÝnovice,aschollingjr@prnewswire.com,649-690-1072,45.0,Familia Camarena Silver,18.0,750,15.00,E AND J GALLO WINERY,TEQUILA
160471,1438399438127,531340,view,375730,NaN,2015-08-01 03:23:58.127,Johnny,Roden,6/3/94,Male,...,Barranqueras,jroden4@google.cn,916-350-6280,5.0,Dekuyper Sampler Pack,23.0,1127,12.81,Jim Beam Brands,DECANTERS & SPECIALTY PACKAGES

In [80]:
df = df[df["event"]=="transaction"]
df

,timestamp,visitorid,event,itemid,transactionid,fechahora,nombre,apellido,nacimiento,genero,...,ciudad,correo,telefono,categoria_id,nombre_producto,marca_id,volumen,precio,marca,categoria
6,1433222276276,599528,transaction,356475,4000.0,2015-06-02 05:17:56.276,Samuel,Ward,4/6/89,Male,...,Wangjing,sward0@tamu.edu,86-(786)608-5061,9.0,Crown Royal Honey,1.0,750,22.49,Diageo Americas,CANADIAN WHISKIES
7,1433222276276,599528,transaction,356475,4000.0,2015-06-02 05:17:56.276,Samuel,Ward,4/6/89,Male,...,Wangjing,sward0@tamu.edu,86-(786)608-5061,74.0,Dekuyper Sour Peach Pucker,23.0,200,2.27,Jim Beam Brands,PEACH SCHNAPPS
14,1433193500981,121688,transaction,15335,11117.0,2015-06-01 21:18:20.981,Willie,Gonzales,6/29/72,Male,...,El Corozo,wgonzales1@apache.org,58-(265)301-3397,9.0,Crown Royal Regal Apple Mini,1.0,300,11.03,Diageo Americas,CANADIAN WHISKIES
21,1433193915008,552148,transaction,81345,5444.0,2015-06-01 21:25:15.008,Betty,Spencer,9/2/83,Female,...,Jinhua,bspencer2@shutterfly.com,86-(195)193-9042,9.0,Crown Royal Regal Apple,1.0,200,7.08,Diageo Americas,CANADIAN WHISKIES
44,1433176736375,102019,transaction,150318,13556.0,2015-06-01 16:38:56.375,Beverly,Jordan,1/15/72,Female,...,Salvacion,bjordan3@vimeo.com,63-(652)708-7688,9.0,Crown Royal Xr Canadian Whiskey,1.0,750,98.99,Diageo Americas,CANADIAN WHISKIES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160440,1438377176570,1050575,transaction,31640,8354.0,2015-07-31 21:12:56.570,Marlie,de Glanville,5/11/93,Female,...,Sarana,mdeglanvillejx@is.gd,316-501-5100,8.0,Bacardi Superior Rum Mini,13.0,500,8.31,"Bacardi U.S.A., Inc.",PUERTO RICO & VIRGIN ISLANDS RUM
160442,1438379878779,861299,transaction,456602,3643.0,2015-07-31 21:57:58.779,Martha,White,6/27/89,Female,...,Xinmatou,mwhiteqz@w3.org,86-(693)411-7140,1.0,Chivas Regal 18 Year,7.0,750,52.49,Pernod Ricard USA/Austin Nichols,SCOTCH WHISKIES
160453,1438357730123,855941,transaction,235771,4385.0,2015-07-31 15:48:50.123,Ella,Danilin,5/20/99,Female,...,San Antonio SuchitepÌ©quez,edanilinjy@discuz.net,376-820-7829,3.0,Calvert Extra Bl Whiskey,9.0,1000,10.32,Luxco-St Louis,BLENDED WHISKIES
160460,1438355560300,548772,transaction,29167,13872.0,2015-07-31 15:12:40.300,Richard,Frazier,2/25/62,Male,...,Xamba,rfrazierj2@dell.com,86-(786)874-8436,45.0,1800 Silver Tequila,21.0,375,12.75,Proximo,TEQUILA
160461,1438358989163,1051054,transaction,312728,17579.0,2015-07-31 16:09:49.163,Conney,Tomisch,8/31/93,Male,...,Gereshk,ctomischib@google.com.hk,520-342-0060,9.0,Crown Royal Hand Selected Barrel #2648,1.0,750,41.24,Diageo Americas,CANADIAN WHISKIES

In [71]:
transaction_category_counts = df.groupby('transactionid')['categoria'].nunique()

# Step 2: Filter for transactions with more than 2 categories
transactions_with_more_than_2 = transaction_category_counts[transaction_category_counts > 2]

df_reglas_asociacion = df[["transactionid","categoria"]]

df_reglas_asociacion.sort_values(by="transactionid",ascending=True).head()

        transactionid                           categoria
17016             0.0                     SCOTCH WHISKIES
140372            1.0          HIGH PROOF BEER - AMERICAN
3927              2.0                  AMERICAN COCKTAILS
27350             3.0                      CREAM LIQUEURS
9048              4.0  MISC. IMPORTED CORDIALS & LIQUEURS

In [82]:
basket_sizes = df.groupby('transactionid').size()
valid_baskets = basket_sizes[basket_sizes > 1].index
df_filtered = df[df['transactionid'].isin(valid_baskets)]
df_filtered.sort_values(by="transactionid",ascending=True)

,timestamp,visitorid,event,itemid,transactionid,fechahora,nombre,apellido,nacimiento,genero,...,ciudad,correo,telefono,categoria_id,nombre_producto,marca_id,volumen,precio,marca,categoria
107199,1431978994534,288956,transaction,239235,12.0,2015-05-18 19:56:34.534,Bram,Schubbert,11/4/97,Male,...,ConcÌ_rdia,bschubbertnq@wikipedia.org,159-640-0656,11.0,Longrow Cv,63.0,750,51.27,Anchor Distilling (PREISS IMPORTS),SINGLE MALT SCOTCH
107772,1431978994534,288956,transaction,432742,12.0,2015-05-18 19:56:34.534,Bram,Schubbert,11/4/97,Male,...,ConcÌ_rdia,bschubbertnq@wikipedia.org,159-640-0656,24.0,Berry's Own 10yr Panama Rum,63.0,750,75.00,Anchor Distilling (PREISS IMPORTS),FLAVORED RUM
5205,1433448499720,527277,transaction,351124,23.0,2015-06-04 20:08:19.720,James,Harper,8/25/44,Male,...,Aqqan,jharperai@amazon.de,86-(194)459-9955,42.0,Ciroc Apple,1.0,750,27.74,Diageo Americas,IMPORTED VODKA - MISC
5532,1433448499720,527277,transaction,397642,23.0,2015-06-04 20:08:19.720,James,Harper,8/25/44,Male,...,Aqqan,jharperai@amazon.de,86-(194)459-9955,42.0,Ciroc Peach,1.0,50,44.93,Diageo Americas,IMPORTED VODKA - MISC
5730,1433448499642,527277,transaction,93556,23.0,2015-06-04 20:08:19.642,James,Harper,8/25/44,Male,...,Aqqan,jharperai@amazon.de,86-(194)459-9955,43.0,Sambuca Romana Liqueur,1.0,603,19.73,Diageo Americas,MISC. IMPORTED CORDIALS & LIQUEURS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57855,1439949233505,795731,transaction,442610,17662.0,2015-08-19 01:53:53.505,Ralph,Allen,5/1/79,Male,...,IlÛªinskiy Pogost,rallen14@cornell.edu,7-(698)581-8964,20.0,Southern Comfort,3.0,1000,19.46,"Sazerac Co., Inc.",WHISKEY LIQUEUR
57255,1439924299494,465862,transaction,334401,17663.0,2015-08-18 18:58:19.494,Carlos,Elliott,9/25/74,Male,...,NuwaybiÛ÷a,celliott1k@omniture.com,20-(609)654-8150,43.0,Caravella Limoncello Mini,19.0,600,8.93,Sazerac North America,MISC. IMPORTED CORDIALS & LIQUEURS
57472,1439924299698,465862,transaction,180349,17663.0,2015-08-18 18:58:19.698,Carlos,Elliott,9/25/74,Male,...,NuwaybiÛ÷a,celliott1k@omniture.com,20-(609)654-8150,5.0,Pinnacle Peach w/ Punch Dispenser,23.0,750,11.03,Jim Beam Brands,DECANTERS & SPECIALTY PACKAGES
108766,1432072691718,163561,transaction,260256,17669.0,2015-05-19 21:58:11.718,Sara,Sullivan,4/12/57,Female,...,Saint-Ìätienne,ssullivan41@dot.gov,33-(970)190-1562,7.0,Smirnoff Sorbet Light Pineapple Coconut Mini,1.0,500,8.58,Diageo Americas,VODKA FLAVORED
108763,1432072691609,163561,transaction,132418,17669.0,2015-05-19 21:58:11.609,Sara,Sullivan,4/12/57,Female,...,Saint-Ìätienne,ssullivan41@dot.gov,33-(970)190-1562,2.0,Prichard's Single Malt Whiskey,66.0,750,38.99,Aveniu Brands,STRAIGHT BOURBON WHISKIES

In [83]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# Step 2: Create a one-hot encoded DataFrame
one_hot = pd.get_dummies(df_filtered['itemid'])
one_hot['transactionid'] = df_filtered['transactionid']
basket = one_hot.groupby('transactionid').max()

# Step 3: Generate frequent itemsets
frequent_itemsets = apriori(basket, min_support=0.001, use_colnames=True)

# Step 4: Generate association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

# Display the rules

# Optional: Check the number of transactions before and after filtering
print(f"Original number of transactions: {df['transactionid'].nunique()}")
print(f"Number of transactions after removing single-item baskets: {df_filtered['transactionid'].nunique()}")

rules.sort_values(by="support",ascending=False)

Original number of transactions: 16839
Number of transactions after removing single-item baskets: 2542

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
46,(445351),(213834),0.015342,0.035012,0.015342,1.000000,28.561798,0.014805,inf,0.980024
34,(171878),(461686),0.003934,0.023210,0.003541,0.900000,38.776271,0.003449,9.767899,0.978059
48,(218794),(461686),0.003147,0.023210,0.003147,1.000000,43.084746,0.003074,inf,0.979874
8,(32581),(461686),0.003147,0.023210,0.003147,1.000000,43.084746,0.003074,inf,0.979874
21,(78268),(449391),0.002754,0.003541,0.002360,0.857143,242.095238,0.002351,6.975216,0.998619
...,...,...,...,...,...,...,...,...,...,...
41,(218746),(213834),0.001574,0.035012,0.001180,0.750000,21.421348,0.001125,3.859953,0.954820
40,(307733),(185082),0.001574,0.001180,0.001180,0.750000,635.500000,0.001178,3.995279,1.000000
39,(185082),(307733),0.001180,0.001574,0.001180,1.000000,635.500000,0.001178,inf,0.999606
38,(185082),(297145),0.001180,0.001574,0.001180,1.000000,635.500000,0.001178,inf,0.999606
58,(265846),(256146),0.001180,0.004721,0.001180,1.000000,211.833333,0.001175,inf,0.996455

In [39]:
df2 = pd.crosstab(df_reglas_asociacion['transactionid'], df_reglas_asociacion['categoria'])
df2.head()

categoria,100 PROOF VODKA,AMARETTO - IMPORTED,AMERICAN ALCOHOL,AMERICAN AMARETTO,AMERICAN COCKTAILS,AMERICAN DRY GINS,AMERICAN GRAPE BRANDIES,AMERICAN RUMS,AMERICAN SLOE GINS,ANISETTE,...,TENNESSEE WHISKIES,TEQUILA,TRIPLE SEC,TROPICAL FRUIT SCHNAPPS,VODKA 80 PROOF,VODKA FLAVORED,WATERMELON SCHNAPPS,WHISKEY LIQUEUR,WHITE CREME DE CACAO,WHITE CREME DE MENTHE
transactionid,,,,,,,,,,,,,,,,,,,,,
0.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2.0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
df2.to_csv('csv/carritos_transacciones.csv')

In [35]:
def encode(item_freq):
    res = 0
    if item_freq > 0:
        res = 1
    return res
    
basket_input = df2.applymap(encode)
basket_input.head()

/tmp/ipykernel_108082/962722212.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket_input = df2.applymap(encode)

categoria,100 PROOF VODKA,AMARETTO - IMPORTED,AMERICAN ALCOHOL,AMERICAN AMARETTO,AMERICAN COCKTAILS,AMERICAN DRY GINS,AMERICAN GRAPE BRANDIES,AMERICAN RUMS,AMERICAN SLOE GINS,ANISETTE,...,TENNESSEE WHISKIES,TEQUILA,TRIPLE SEC,TROPICAL FRUIT SCHNAPPS,VODKA 80 PROOF,VODKA FLAVORED,WATERMELON SCHNAPPS,WHISKEY LIQUEUR,WHITE CREME DE CACAO,WHITE CREME DE MENTHE
transactionid,,,,,,,,,,,,,,,,,,,,,
0.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2.0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
basket_input.to_csv('csv/carritos_transacciones_encoded.csv')

In [72]:


from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

frequent_itemsets = apriori(df2.astype('bool'), min_support=0.001, use_colnames=True)
frequent_itemsets

      support                                     itemsets
0    0.005345                            (100 PROOF VODKA)
1    0.001188                        (AMARETTO - IMPORTED)
2    0.003207                           (AMERICAN ALCOHOL)
3    0.004098                          (AMERICAN AMARETTO)
4    0.064849                         (AMERICAN COCKTAILS)
..        ...                                          ...
136  0.001425         (VODKA FLAVORED, SINGLE MALT SCOTCH)
137  0.001128         (TEQUILA, STRAIGHT BOURBON WHISKIES)
138  0.002375  (STRAIGHT BOURBON WHISKIES, VODKA FLAVORED)
139  0.002197                    (TEQUILA, VODKA FLAVORED)
140  0.001306             (VODKA FLAVORED, VODKA 80 PROOF)

[141 rows x 2 columns]

In [76]:
rules = association_rules(frequent_itemsets, metric="lift")

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(STRAIGHT BOURBON WHISKIES),(AMERICAN DRY GINS),0.049409,0.016687,0.001010,0.020433,1.224435,0.000185,1.003823,0.192824
1,(AMERICAN DRY GINS),(STRAIGHT BOURBON WHISKIES),0.016687,0.049409,0.001010,0.060498,1.224435,0.000185,1.011803,0.186407
2,(IMPORTED VODKA),(SINGLE MALT SCOTCH),0.050537,0.043055,0.001782,0.035253,0.818785,-0.000394,0.991913,-0.189037
3,(SINGLE MALT SCOTCH),(IMPORTED VODKA),0.043055,0.050537,0.001782,0.041379,0.818785,-0.000394,0.990447,-0.187837
4,(SINGLE MALT SCOTCH),(MISCELLANEOUS BRANDIES),0.043055,0.012412,0.002791,0.064828,5.223118,0.002257,1.056049,0.844921

In [77]:
rules.sort_values(["support", "confidence","lift"],axis = 0, ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
5,(MISCELLANEOUS BRANDIES),(SINGLE MALT SCOTCH),0.012412,0.043055,0.002791,0.224880,5.223118,0.002257,1.234577,0.818705
4,(SINGLE MALT SCOTCH),(MISCELLANEOUS BRANDIES),0.043055,0.012412,0.002791,0.064828,5.223118,0.002257,1.056049,0.844921
3,(SINGLE MALT SCOTCH),(IMPORTED VODKA),0.043055,0.050537,0.001782,0.041379,0.818785,-0.000394,0.990447,-0.187837
2,(IMPORTED VODKA),(SINGLE MALT SCOTCH),0.050537,0.043055,0.001782,0.035253,0.818785,-0.000394,0.991913,-0.189037
1,(AMERICAN DRY GINS),(STRAIGHT BOURBON WHISKIES),0.016687,0.049409,0.001010,0.060498,1.224435,0.000185,1.011803,0.186407
0,(STRAIGHT BOURBON WHISKIES),(AMERICAN DRY GINS),0.049409,0.016687,0.001010,0.020433,1.224435,0.000185,1.003823,0.192824

In [78]:
rules.to_csv('csv/carritos_transacciones_reglas_asociacion_categoria.csv')

In [79]:
from sqlalchemy import create_engine
import numpy as np

engine = create_engine('postgresql://data_analytics:data_analytics@127.0.0.1:5432/data_analytics')
rules['new_antecedents'] = rules['antecedents'].apply(lambda x: np.array(list(x)))
rules['new_antecedents'] = rules['new_antecedents'].astype(str)
rules['new_consequents'] = rules['consequents'].apply(lambda x: np.array(list(x)))
rules['new_consequents'] = rules['new_consequents'].astype(str)

rules[["new_antecedents","new_consequents","antecedent support","consequent support","support","confidence","lift"]].to_sql('reglas_asociacion_categorias', engine, if_exists='replace', index=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric,new_antecedents,new_consequents
0,(STRAIGHT BOURBON WHISKIES),(AMERICAN DRY GINS),0.049409,0.016687,0.001010,0.020433,1.224435,0.000185,1.003823,0.192824,['STRAIGHT BOURBON WHISKIES'],['AMERICAN DRY GINS']
1,(AMERICAN DRY GINS),(STRAIGHT BOURBON WHISKIES),0.016687,0.049409,0.001010,0.060498,1.224435,0.000185,1.011803,0.186407,['AMERICAN DRY GINS'],['STRAIGHT BOURBON WHISKIES']
2,(IMPORTED VODKA),(SINGLE MALT SCOTCH),0.050537,0.043055,0.001782,0.035253,0.818785,-0.000394,0.991913,-0.189037,['IMPORTED VODKA'],['SINGLE MALT SCOTCH']
3,(SINGLE MALT SCOTCH),(IMPORTED VODKA),0.043055,0.050537,0.001782,0.041379,0.818785,-0.000394,0.990447,-0.187837,['SINGLE MALT SCOTCH'],['IMPORTED VODKA']
4,(SINGLE MALT SCOTCH),(MISCELLANEOUS BRANDIES),0.043055,0.012412,0.002791,0.064828,5.223118,0.002257,1.056049,0.844921,['SINGLE MALT SCOTCH'],['MISCELLANEOUS BRANDIES']
5,(MISCELLANEOUS BRANDIES),(SINGLE MALT SCOTCH),0.012412,0.043055,0.002791,0.224880,5.223118,0.002257,1.234577,0.818705,['MISCELLANEOUS BRANDIES'],['SINGLE MALT SCOTCH']